// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzfcylfamjtlppscfmuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6ZmN5bGZhbWp0bHBwc2NmbXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjEwMDksImV4cCI6MjA2MzkzNzAwOX0.QdxCg6EvauP3Qi8x5oRJ4hDUZflo-jWR13TD-CKu9cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);